version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/node:16.15

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Lint
          command: yarn lint

      - run:
          name: Check Types
          command: yarn check-types

      - run: yarn build
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: DEV
