export enum FlowIdentifiers {
  INVESTMENT_HISTORY = 'INVESTMENT_HISTORY',
  RECURRING_INVESTMENTS = 'RECURRING_INVESTMENTS',
  DIVIDEND_REINVESTING = 'DIVIDEND_REINVESTING',
  WITHDRAW_FUNDS = 'WITHDRAW_FUNDS',
  BANK_ACCOUNT = 'BANK_ACCOUNT',
  ACCOUNT_ACTIVITY = 'ACCOUNT_ACTIVITY',
  REMOVE_ACCOUNT = 'REMOVE_ACCOUNT',

  EMAIL_ADDRESS = 'EMAIL_ADDRESS',
  PHONE_NUMBER = 'PHONE_NUMBER',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',

  NAME = 'NAME',
  CHANGE_AVATAR = 'CHANGE_AVATAR',
  BENEFICIARY_NAME = 'BENEFICIARY_NAME',
  UPDATE_PROFILE_PICTURE = 'UPDATE_PROFILE_PICTURE',
  UPDATE_ADDRESS = 'UPDATE_ADDRESS',
  DOCUMENTS = 'DOCUMENTS',
}

export enum QueryFlowIdentifiers {
  MANAGE_INVESTMENT = 'manage-investment',
  MANAGE_BANK_ACCOUNT = 'manage-bank-account',
  MANAGE_PASSWORD = 'manage-password',
  MANAGE_RECURRING_INVESTMENT = 'manage-recurring-investment',
}
