export enum Identifiers {
  INITIAL_INVESTMENT = 'INITIAL_INVESTMENT',

  RECURRING_INVESTMENT = 'RECURRING_INVESTMENT',
  RECURRING_INVESTMENT_AMOUNT = 'RECURRING_INVESTMENT_AMOUNT',
  RECURRING_INVESTMENT_INTERVAL = 'RECURRING_INVESTMENT_INTERVAL',
  RECURRING_INVESTMENT_DATE = 'RECURRING_INVESTMENT_DATE',
  RECURRING_DEPOSIT_SCHEDULE = 'RECURRING_DEPOSIT_SCHEDULE',

  AUTOMATIC_DIVIDENT_REINVESTMENT = 'AUTOMATIC_DIVIDENT_REINVESTMENT',
  SUBSCRIPTION_AGREEMENTS = 'SUBSCRIPTION_AGREEMENTS',
  INVESTMENT_VERIFICATION = 'INVESTMENT_VERIFICATION',
  INVESTMENT_COMPLETED = 'INVESTMENT_COMPLETED',
}
