export enum FlowStepIdentifiers {
  LOADING = 'LOADING',
  CURRENT_COMPLIANCE = 'CURRENT_COMPLIANCE',
  NEW_COMPLIANCE = 'NEW_COMPLIANCE',
  FINRA_INSTITUTION = 'FINRA_INSTITUTION',
  COMPANY_TICKER_SYMBOLS = 'COMPANY_TICKER_SYMBOLS',
  SENIOR_POLITICAL_FIGURES = 'SENIOR_POLITICAL_FIGURES',
  CONFIRMATION = 'CONFIRMATION',
}
