export enum FlowStepIdentifiers {
  LOADING = 'LOADING',
  CURRENT_NAME = 'CURRENT_NAME',
  NEW_NAME = 'NEW_NAME',
  CONFIRMATION = 'CONFIRMATION',
  IDENTIFICATION_DOCUMENT = 'IDENTIFICATION_DOCUMENT',
}
