export enum FlowStepIdentifiers {
  LOADING = 'LOADING',
  CURRENT_PHONE_NUMBER = 'CURRENT_PHONE_NUMBER',
  NEW_PHONE_NUMBER = 'NEW_PHONE_NUMBER',
  CONFIRMATION = 'CONFIRMATION',
  AUTHENTICATION_CODE = 'AUTHENTICATION_CODE',
}
