export enum Identifiers {
  ACCOUNT_SELECTION = 'ACCOUNT_SELECTION',
  INVESTMENT_AMOUNT = 'INVESTMENT_AMOUNT',

  RECURRING_INVESTMENT = 'RECURRING_INVESTMENT',
  RECURRING_INVESTMENT_AMOUNT = 'RECURRING_INVESTMENT_AMOUNT',
  RECURRING_INVESTMENT_INTERVAL = 'RECURRING_INVESTMENT_INTERVAL',
  RECURRING_INVESTMENT_DATE = 'RECURRING_INVESTMENT_DATE',
  RECURRING_DEPOSIT_SCHEDULE = 'RECURRING_DEPOSIT_SCHEDULE',

  OPT_IN_AUTOMATIC_DIVIDEND_REINVESTMENT = 'OPT_IN_AUTOMATIC_DIVIDEND_REINVESTMENT',
  SUBSCRIPTION_AGREEMENT = 'SUBSCRIPTION_AGREEMENT',

  INVESTMENT_AGREEMENTS = 'INVESTMENT_AGREEMENTS',
  INVESTMENT_VERIFICATION = 'INVESTMENT_VERIFICATION',
  INVESTMENT_COMPLETED = 'INVESTMENT_COMPLETED',
}
