export enum Identifiers {
  LANDING = 'LANDING',
  ACCOUNT_SELECTION = 'ACCOUNT_SELECTION',

  BANK_ACCOUNT_LANDING = 'BANK_ACCOUNT_LANDING',
  BANK_ACCOUNT_SELECTION = 'BANK_ACCOUNT_SELECTION',
  BANK_ACCOUNT_CONFIRMATION = 'BANK_ACCOUNT_CONFIRMATION',

  ONE_TIME_INVESTMENT = 'ONE_TIME_INVESTMENT',

  RECURRING_INVESTMENT = 'RECURRING_INVESTMENT',
  RECURRING_INVESTMENT_AMOUNT = 'RECURRING_INVESTMENT_AMOUNT',
  RECURRING_INVESTMENT_INTERVAL = 'RECURRING_INVESTMENT_INTERVAL',
  RECURRING_INVESTMENT_DATE = 'RECURRING_INVESTMENT_DATE',
  RECURRING_DEPOSIT_SCHEDULE = 'RECURRING_DEPOSIT_SCHEDULE',

  AUTOMATIC_DIVIDENT_REINVESTMENT = 'AUTOMATIC_DIVIDENT_REINVESTMENT',
  SUBSCRIPTION_AGREEMENTS = 'SUBSCRIPTION_AGREEMENTS',
  INVESTMENT_VERIFICATION = 'INVESTMENT_VERIFICATION',
  INVESTMENT_COMPLETED = 'INVESTMENT_COMPLETED',

  FULL_NAME = 'FULL_NAME',
  PERMANENT_ADDRESS = 'PERMANENT_ADDRESS',
  DATE_OF_BIRTH = 'DATE_OF_BIRTH',
  RESIDENCY_STATUS = 'RESIDENCY_STATUS',
  RESIDENCY_GREEN_CARD = 'RESIDENCY_GREEN_CARD',
  RESIDENCY_VISA = 'RESIDENCY_VISA',
  IDENTIFICATION_DOCUMENTS = 'IDENTIFICATION_DOCUMENTS',

  CORPORATE_APPLICANT_DETAILS = 'CORPORATE_APPLICANT_DETAILS',
  CORPORATE_APPLICANT_IDENTIFICATION = 'CORPORATE_APPLICANT_IDENTIFICATION',
  CORPORATE_APPLICANT_LIST = 'CORPORATE_APPLICANT_LIST',
  APPLICANT_ADDRESS = 'APPLICANT_ADDRESS',

  BUSINESS_ADDRESS = 'BUSINESS_ADDRESS',
  CORPORATION_INFORMATION = 'CORPORATION_INFORMATION',
  CORPORATION_LEGAL_NAME = 'CORPORATION_LEGAL_NAME',
  CORPORATION_TYPE = 'CORPORATION_TYPE',
  DOCUMENTS_FOR_CORPORATION = 'DOCUMENTS_FOR_CORPORATION',
}
