export enum FlowStepIdentifiers {
  LOADING = 'LOADING',
  CURRENT_EMAIL_ADDRESS = 'CURRENT_EMAIL_ADDRESS',
  NEW_EMAIL_ADDRESS = 'NEW_EMAIL_ADDRESS',
  CONFIRMATION = 'CONFIRMATION',
  AUTHENTICATION_CODE = 'AUTHENTICATION_CODE',
}
