export enum Identifiers {
  ACCOUNT_TYPE = 'ACCOUNT_TYPE',
  FULL_NAME = 'FULL_NAME',
  PHONE_NUMBER = 'PHONE_NUMBER',
  EMPLOYMENT_STATUS = 'EMPLOYMENT_STATUS',
  EMPLOYMENT_DETAILS = 'EMPLOYMENT_DETAILS',
  NET_WORTH_AND_INCOME = 'NET_WORTH_AND_INCOME',
  EXPERIENCE = 'EXPERIENCE',
  RESIDENCY_STATUS = 'RESIDENCY_STATUS',
  RESIDENCY_GREEN_CARD = 'RESIDENCY_GREEN_CARD',
  RESIDENCY_VISA = 'RESIDENCY_VISA',
}
