export enum Identifiers {
  FULL_NAME = 'FULL_NAME',
  EMPLOYMENT_STATUS = 'EMPLOYMENT_STATUS',
  EMPLOYMENT_DETAILS = 'EMPLOYMENT_DETAILS',
  NET_WORTH_AND_INCOME = 'NET_WORTH_AND_INCOME',
  EXPERIENCE = 'EXPERIENCE',
  SOCIAL_SECURITY_NUMBER = 'SOCIAL_SECURITY_NUMBER',
  SOCIAL_SECURITY_NUMBER_VALIDATION = 'SOCIAL_SECURITY_NUMBER_VALIDATION',
}
