name: functions-github-actions
on:
  push:
    branches:
      - development
      - integrations
      - staging
      - main
jobs:
  build-check-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment
        run: |
          CURRENT_BRANCH=${GITHUB_REF##*/} 
          echo "Current branch: ${CURRENT_BRANCH}"
          if [ $CURRENT_BRANCH == "development" ]; then
            ENVIRONMENT="DEVELOPMENT"
          elif [ $CURRENT_BRANCH == "integrations" ]; then
            ENVIRONMENT="INTEGRATIONS"
          elif [ $CURRENT_BRANCH == "staging" ]; then
            ENVIRONMENT="STAGING"
          elif [ $CURRENT_BRANCH == "main" ]; then
            ENVIRONMENT="PRODUCTION"
          else
            echo "Wrong branch";
            exit 1;
          fi
          echo "Current environment: ${ENVIRONMENT}"
          echo "ENVIRONMENT=${ENVIRONMENT}" >> $GITHUB_ENV
      - uses: shaunco/ssh-agent@git-repo-mapping # this action will configure git to use the right SSH key per each repository.
        with:
          ssh-private-key: |
            ${{ secrets.COMMON_SSH_PRIVATE_KEY}}
          repo-mappings: |
            github.com/JoinReinvest/reinvest-fe-common
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Sentry Release
        uses: getsentry/action-release@v1.3.1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: reinvest
          SENTRY_PROJECT: reinvest-web
        with:
          environment: ${{ env.ENVIRONMENT }}
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Authenticate with private NPM package
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: "Install dependencies"
        run: yarn install
      - name: "Install app dependencies"
        working-directory: ./reinvest-web-app
        run: yarn install
      #      - name: "Linter"
      #        working-directory: ./reinvest-web-app
      #        run: yarn install | yarn lint
      #      - name: "Check types"
      #        working-directory: ./reinvest-web-app
      #        run: yarn check-types
      - name: "Deploy to AWS"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_COGNITO_USER_POOL_ID: ${{ secrets[format('{0}_AWS_COGNITO_USER_POOL_ID', env.ENVIRONMENT)] }}
          AWS_COGNITO_CLIENT_ID: ${{ secrets[format('{0}_AWS_COGNITO_CLIENT_ID', env.ENVIRONMENT)] }}
          AWS_COGNITO_REGION: ${{secrets.AWS_COGNITO_REGION}}
          SITE_NAME: ${{ secrets.SITE_NAME }}
          REINVEST_SITE_URL: ${{ secrets.REINVEST_SITE_URL }}
          API_URL: ${{ secrets[format('{0}_API_URL', env.ENVIRONMENT)] }}
          ANALYZE: ${{ secrets.ANALYZE }}
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
          GOOGLE_MAPS_PLACES_URL: ${{ secrets.GOOGLE_MAPS_PLACES_URL }}
          GOOGLE_MAPS_AUTOCOMPLETE_URL: ${{ secrets.GOOGLE_MAPS_AUTOCOMPLETE_URL }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        run: |
          environment=${{env.ENVIRONMENT}}
          yarn deploy --stage "${environment,,}"
