export enum Identifiers {
  EMAIL = 'EMAIL',
  REFERRAL_CODE = 'REFERRAL_CODE',
  REFERRAL_CODE_VERIFICATION = 'REFERRAL_CODE_VERIFICATION',
  PASSWORD = 'PASSWORD',
  AUTHENTICATION_CODE = 'AUTHENTICATION_CODE',
  FLOW_COMPLETION = 'FLOW_COMPLETION',
}
